### PR TITLE
Added standalone template certificate.ymlj2

### PR DESCRIPTION
**Pull request by christian-casecommons**
Adds a generic/standalone certificate template. To use, open ./group_vars/env/vars.yml and modify as so:

```yaml
Config.Certificates:
  DevCasebookPlatformOrg:
    DomainName: *.dev.casebookplatform.org
    SubjectAlternativeNames:
      - www.casebook.com
    ValidationOptions:
      - DomainName: *.casebookplatform.org
        ValidationDomain: casebookplatform.org
```

### CODE REVIEW

**Comment by pemacc** [comment]
Either these changes should be reflected in README file or needs documentation in some shape or form. it applies to cloudfront, s3 buckets etc.

**Comment by christian-casecommons** [comment]
I'll add this to aws-docs momentarily

**Comment by pemacc** [comment]
Going forward, Lets not accept any pull request without proper documentation.

**Comment by christian-casecommons** [comment]
Sounds good to me

**Comment by christian-casecommons** [comment]
@pemacc I've updated the aws-docs pull request to cover usage of this template.

https://github.com/Casecommons/aws-docs/pull/5
https://github.com/christian-casecommons/aws-docs/blob/62f7a978eff06b87b010155b3c2610f4478195df/content/misc/index.md

**Comment by christian-casecommons** [comment]
And again

https://github.com/Casecommons/aws-cloudformation/pull/11

**Pull request merged**
